### ISSUE TITLE
cuda driver compatibility issue 

### ISSUE THREAD

**Issue by Jushan-Randy-Chen** [liboyue/Network-Distributed-Algorithm#3]
Hi,

I encountered the following issue when running the code:
```
(Randy) randy233@Randy-Desktop:/mnt/c/Users/Randy666/Documents/projects/ICON_lab/Network-Distributed-Algorithm/experiments/convex$ python logistic_regression.py
INFO 10:47:30.9716 5965 utils.py:160] NumExpr defaulting to 6 threads.
INFO 10:47:31.1224 5965 logistic_regression.py:63] Initializing using GPU
Process Process-1:
Traceback (most recent call last):
  File "/home/randy233/anaconda3/envs/Randy/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/randy233/anaconda3/envs/Randy/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/Randy666/Documents/projects/ICON_lab/Network-Distributed-Algorithm/nda/problems/logistic_regression.py", line 85, in _init
    self.cuda()
  File "/mnt/c/Users/Randy666/Documents/projects/ICON_lab/Network-Distributed-Algorithm/nda/problems/problem.py", line 93, in cuda
    self.__dict__[k] = xp.array(self.__dict__[k])
  File "/home/randy233/anaconda3/envs/Randy/lib/python3.10/site-packages/cupy/_creation/from_data.py", line 46, in array
    return _core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/_core/core.pyx", line 2357, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2381, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2513, in cupy._core.core._array_default
  File "cupy/_core/core.pyx", line 136, in cupy._core.core.ndarray.__new__
  File "cupy/_core/core.pyx", line 224, in cupy._core.core._ndarray_base._init
  File "cupy/cuda/memory.pyx", line 742, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1419, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1439, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/device.pyx", line 48, in cupy.cuda.device.get_device_id
  File "cupy_backends/cuda/api/runtime.pyx", line 178, in cupy_backends.cuda.api.runtime.getDevice
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInsufficientDriver: CUDA driver version is insufficient for CUDA runtime version
^CTraceback (most recent call last):
  File "/mnt/c/Users/Randy666/Documents/projects/ICON_lab/Network-Distributed-Algorithm/experiments/convex/logistic_regression.py", line 26, in <module>
    p = LogisticRegression(n_agent=n_agent, m=m, dim=dim, noise_ratio=0.05, graph_type='er', kappa=kappa, graph_params=0.3)
  File "/mnt/c/Users/Randy666/Documents/projects/ICON_lab/Network-Distributed-Algorithm/nda/problems/logistic_regression.py", line 68, in __init__
    norm = q.get()
  File "/home/randy233/anaconda3/envs/Randy/lib/python3.10/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
  File "/home/randy233/anaconda3/envs/Randy/lib/python3.10/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/randy233/anaconda3/envs/Randy/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/randy233/anaconda3/envs/Randy/lib/python3.10/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```
I wonder how should I check my current CUDA version, and should I download the latest CUDA driver?

**Comment by liboyue** [comment]
`nvcc --version` to check CUDA version. I think you can update CUDA driver through package managers but I'm not sure.

**Comment by Jushan-Randy-Chen** [comment]
thank you! I also wonder if you have any suggestions on how to solve a robotic trajectory optimization problem using this code?

**Comment by liboyue** [comment]
Sorry, this is beyond my knowledge. This repo is designed for quick prototyping distributed optimization algorithms, as long as you can formulate your problem to a optimization problem, then you can call all optimization algorithms in this repo to solve it.
